---
sudo: false

language: ruby

services:
- docker

install:
- bundle install

gemfile:
- Gemfile

rvm:
  - 2.5.0

script:
  - rubocop k8s/local_vagrant/Vagrantfile
  - shellcheck k8s/local_vagrant/*.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
