apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wdhw-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wdhw
    spec:
      containers:
      - name: wdhw
        image: dockercloud/hello-world:latest
        ports:
        - containerPort: 80
